#Imporatant SMS
# appveyor is disabled
branches:
  only:
    - dummy

platform:
  - x64 # 64-bit

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - cmd: echo Appveyor is disabled
