language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.0
  - 1
  - nightly
notifications:
  email: false
branches:
  only:
  - master
  - /v(\d+)\.(\d+)\.(\d+)/
matrix:
  allow_failures:
  - julia: 1.0
codecov: true
